baseURL = 'https://songbird-project-blog.pages.dev'
languageCode = 'en-us'
title = 'Songbird Project Blog'
theme = "hugo-bearcub"

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Blog'
    pageRef = '/blog'
    weight = 20
